name: "SimpleCov Report"
description: "SimpleCov Report"
author: fukumone|pinnacles
branding:
  icon: check-square
  color: green
inputs:
  failedThreshold:
    description: Failed threshold
    default: "90"
    required: false
  headRefCoveragePath:
    description: "json path"
    default: "coverage/coverage.json"
    required: false
  baseRefCoveragePath:
    description: "json path"
    default: "baseref_coverage/coverage.json"
    required: false
  token:
    description: "Github token"
    required: true
  baseBranch:
    description: "Compare base branch coverage results"
    required: true
  headSha:
    description: "head sha"
    required: true
runs:
  using: 'node16'
  main: "dist/index.js"
